version: '3'
services:


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_produtos 
    links:
      - db 

  db:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password 
    command: --init-file /init.sql
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=db_produtos
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./init.sql:/init.sql

  
  produtos:
    # command: mvn clean install
    build:
      context: ./
      dockerfile: ./produtos/Dockerfile
    image: produtos/api

    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "./produtos:/home/produtos"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_produtos
#      - MYSQL_ROOT_HOST= '%'
    links:
      - db


  
      
 
